apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-microservice-example
      service: auth
  template:
    metadata:
      labels:
        app: nodejs-microservice-example
        service: auth
    spec:
      initContainers:
          - name: init-db
            image: busybox:1.28
            command: ['sh', '-c', 'until nslookup auth-database-srv; do echo waiting for auth-database-srv; sleep 2; done']
      containers:
        - name: nodejs-microservice-example-auth
          image: kogab/nodejs-microservice-example-auth
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET

---

apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: nodejs-microservice-example
    service: auth
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000